version: "3.9"

services:

  main:
    container_name: main-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: main-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./main:/var/www/app
      - ./lib:/var/www/app/lib
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - workers
    networks:
      - app-nginx-proxy
    entrypoint: ["php", "-d", "memory_limit=-1", "src/app.php"]

  workers:
    container_name: workers-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: workers-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./workers:/var/www/app
      - ./lib:/var/www/app/lib
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      app-nginx-proxy:
        ipv4_address: 172.26.0.2
    entrypoint: ["php", "-d", "memory_limit=-1", "src/app.php"]

networks:
  app-nginx-proxy:
    name: app-nginx-proxy
    external: true



